version: "3"

services:
  samba:
    image: sambaweb/sambaweb-samba:latest
    ports:
      - "139:139"
      - "445:445"
      - "8080:8080"
    environment:
      - JAVA_DEBUG=true
    volumes:
      - ./:/SambaWeb

  postgres:
    image: sambaweb/sambaweb-postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SambaWeb
    ports:
      - "5432:5432"
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'  -p 5432
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
      - ./.docker/postgresql.conf:/etc/postgresql/postgresql.conf

volumes:
  postgres-data:
